# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: quiestce
services:
  postgresql:
    image: postgres:15.4
    volumes:
      - quiestce-postgres-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=quiestce
      - POSTGRES_PASSWORD=test-for-local-dev-only
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432

volumes:
  quiestce-postgres-db:
